development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:cd0702ba8c26a49412f8dd9e2079b42d@porgy.redistogo.com:11532/
  channel_prefix: line_production
